//
//  DiscoverMusicViewController.swift
//  MyMusicPlayer
//
//  Created by Ger on 2017/12/4.
//  Copyright (c) 2017年 GpfYxh.Ger.com. All rights reserved.
//
//  This file was generated by the Clean Architecture for Swift
//

import UIKit

class DiscoverMusicViewController: BaseViewController {
    
    
    fileprivate lazy var segmentItems :[String] = {
        let items = ["新歌榜","推荐歌曲","经典老歌","每日推荐","私人电台"]
        return items
    }()
    
    fileprivate lazy var subScrollView :ContentScrollView = {
        let scrollView = ContentScrollView(frame: CGRect(x: 0, y: 105, width: Swidth, height: SHeight - 105 - 49))
        scrollView.items = self.segmentItems.count
        scrollView.isPagingEnabled = true
        return scrollView
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationTitle = "发现音乐"
        let segmentControl = SegmentControl(items: segmentItems)
        segmentControl.frame = CGRect(x: 0, y: 64, width: Swidth, height: 40)
        segmentControl.delegate = self
//        segmentControl.selectionIndicatorColor = UIColor.blue
//        segmentControl.labelNormalColor = UIColor.brown
//        segmentControl.labelSelectColor = UIColor.blue
        view.addSubview(segmentControl)
        
        view.addSubview(subScrollView)
        
    }
}

extension DiscoverMusicViewController :SegmentDelegate{
    
    func segmentItemDidClick(tag: Int) {
        if tag < segmentItems.count {
            subScrollView.scrollToTableView(tag)
        }
    }
    
}










