//
//  DiscoverMusicViewController.swift
//  MyMusicPlayer
//
//  Created by Ger on 2017/12/4.
//  Copyright (c) 2017年 GpfYxh.Ger.com. All rights reserved.
//
//  This file was generated by the Clean Architecture for Swift
//

import UIKit


protocol DiscoverMusicViewControllerViewInput : class {

    
}

protocol DiscoverMusicViewControllerViewOutput {
    
    
}


class DiscoverMusicViewController: BaseViewController , DiscoverMusicViewControllerViewInput {
    
    var viewOutput : DiscoverMusicViewControllerViewOutput?

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationTitle = "发现音乐"
        
        let segmentControl = SegmentControl(items: ["新歌榜","推荐歌曲","经典老歌","每日推荐","私人电台",])
        segmentControl.frame = CGRect(x: 0, y: 64, width: Swidth, height: 40)
        view.addSubview(segmentControl)
    }
}

extension DiscoverMusicViewController{
    
}










